spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wedding
    username: root
    password:

springdoc:
  swagger-ui:
    path: /swagger-ui.html

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: project.wedding.*
  configuration:
    map-underscore-to-camel-case: true
