spring:
  datasource:
    url: "jdbc:mysql://localhost/wedding"
    username: "root"
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver


springdoc:
  swagger-ui:
    operations-sorter: method
