version: '3.8'
services:
  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
  mysql:
    image: mysql:8.0.28
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: wedding
      MYSQL_USER: user
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-dev/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
