version: '3.8'
services:
  app:
    build: .
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
  mysql:
    image: mysql:8.0.28
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: wedding
      MYSQL_USER: user
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    ports:
      - "6379:6379"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
