# TODO: Dockerfile 경로 이동에 따른 리팩토링
version: '3.8'
services:
  app:
    image: ${IMAGE_NAME}
    networks:
      - app-network
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://db-npqmf.pub-cdb.ntruss.com:3306/wedding
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./nginx-dev:/etc/nginx
      - ./nginx-dev/certs:/etc/nginx/certs
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
