spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://mysql:3306/wedding

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.wedding.*
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: org.wedding.adapter.out.persistence.mybatis
