spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://mysql:3306/wedding

  session:
    store-type: redis
    data:
      redis:
        host: redis
        port: 6379
        timeout: 1000
        lettuce:
          pool:
            max-active: 8
            max-wait: -1
            max-idle: 8
            min-idle: 0

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.wedding.*
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: org.wedding.adapter.out.persistence.mybatis
