spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wedding
    username: root
    password:

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.wedding.*
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: org.wedding.adapter.out.persistence.mybatis
